/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package unix.commands.graalvm.cat;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

class CatTest {
    @Test void appHasAGreeting() {
        Cat classUnderTest = new Cat();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
