name: Unit Tests (JUnit 5)
on:
  pull_request:
    branches: [ main ]

jobs:
  unit-tests-linux:
    name: Unit Tests on Linux ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
      - name: Generate gradlew wrapper
        run: |
          gradle wrapper
      - name: Run Junit Test - Java
        run: |
          ./gradlew test
      - name: Run Junit Test - Native
        run: |
          ./gradlew nativeTest